QDRANT_COLLECTION_NAME = "test-collection"
QDRANT_URL = "http://qdrant:6333"
QDRANT_KEY = ""
LLM_URL = "http://vllm:8000/v1"
LLM_KEY = "pee-pee-poo-poo"
LLM_MODEL = "Qwen2-VL-72B-Instruct-GPTQ-Int4"
# LLM_MODEL = "Qwen2-VL-7B-Instruct-GPTQ-Int4"
